---
- name: Configuration | Configure pg_hba.conf
  template:
    src: "pg_hba.conf.j2"
    dest: "{{ postgresql_config_path }}/pg_hba.conf"
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_group }}"
    mode: 0600
  notify: reload postgresql
  when: postgresql_hba_entries | length > 0