---
- name: Include RedHat variables
  include_vars: "{{ ansible_os_family }}_{{ ansible_distribution_version.split('.')[0] }}.yml"
  when: ansible_os_family == 'RedHat'

- name: Include Debian variables
  include_vars: "{{ ansible_distribution }}_{{ ansible_distribution_version.split('.')[0] }}.yml"
  when: ansible_os_family == 'Debian'

- name: Install PostgreSQL from OS repository
  include_tasks: "{{ ansible_os_family }}.yml"

- name: Install PostgreSQL from OS repository
  include_tasks: "configuration.yml"
