---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: ${MOLECULE_PLATFORM_IMAGE:-"geerlingguy/docker-ubuntu2004-ansible:latest"}
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  config_options:
    defaults:
      fact_caching: jsonfile
      fact_caching_connection: $MOLECULE_EPHEMERAL_DIRECTORY/.facts
      fact_caching_timeout: 600
      gather_timeout: 20
      interpreter_python: auto
verifier:
  name: testinfra
  options:
    connection: docker
    v: 2